### ISSUE TITLE
briefcase is not compatible with pip v10

### ISSUE THREAD

**Issue by jedie** [pybee/briefcase#117]
briefcase is not compatible with pip v10 ... `./setup.py android -s` runs into:
```
...
  File "/usr/local/lib/python3.6/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/opt/briefcase/briefcase/app.py", line 134, in finalize_options
    pip.utils.ensure_dir(self.download_dir)
AttributeError: module 'pip' has no attribute 'utils'
```

Full output here: https://travis-ci.org/jedie/pybee-docker/builds/366496033

**Comment by andrewleech** [comment]
Oh darn, pip have finished moving all their functions behind an `_internal` module. 

Really don't know why they felt the need to do that :-(

**Comment by freakboy3742** [comment]
@jedie Thanks for the report. I saw a note about this in the release notes for pip10, and had made a note to check if this affected Briefcase. Looks like it does :-)

@andrewleech They've done this because the methods are internal, and as a result, they're not covered by any API backwards compatibility policy. They want to reserve the right to modify their API in future without people complaining.

**Comment by freakboy3742** [comment]
Turns out the fix was pretty simple, so I've just pushed Briefcase v0.2.2 to PyPI.

**Comment by jedie** [comment]
It's not fixed everywhere, see: https://github.com/pybee/briefcase/blob/master/briefcase/app.py#L134
